default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages:
  - pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: check-case-conflict
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: local
    hooks:
      - id: nx-run-many
        name: Nx format/fix and unit tests
        entry: bash -c 'pnpm exec nx run-many --targets=lint:fix,format:fix && pnpm exec nx run-many --targets=test --projects=web,api,postgres'
        language: system
        pass_filenames: false
        require_serial: true
        verbose: true
